### PR TITLE
Add page detailing gem details of state machine and usage guide

### PR DESCRIPTION
**Pull request by autotelik**
This change adds a new page that documents what state machinw we use, where it's docs are
and basic info on how we use it internally to manage page flow and object life cycles

### CODE REVIEW

**Comment by Cruikshanks** [comment]
Sorry @autotelik can't escape somebody checking how you've written it even here 😁 . But a big thank you for thinking to add this to the guides.

@woodpigeon and @reggieb if there is anything you feel should be documented in the work you have been doing please take the time to do so. This time around I don't want documentation to play second fiddle to tests and code.

**Comment by autotelik** [comment]
@Cruikshanks big brother is watching !! just going through the guide lines to ensure I don't get arrested  .. btw I think you have a superfluous dot that causes copy and paste issues  ! ;-)   --ignore-acronyms '**/*.md'**.**

**Comment by Cruikshanks** [comment]
I've read it once over the weekend, but need to go through it again to properly come back on stuff. Initially though would make a suggestion regards where it sits. It's not really a process and more a concept, so would suggest moving it out of the folder `process` into a `concepts` folder. Perhaps when one of us then has time we can cover what the [reform](https://github.com/apotonick/reform) gem is doing for us, and other things of that ilk.

**Comment by autotelik** [comment]
this may as well be  deleted as we are now using a different state machine gem

**Comment by reggieb** [comment]
I disagree - It's useful documentation of the way the state machine works in Waste Exceptions.

**Comment by Cruikshanks** [comment]
I concur with @reggieb . I would suggest we create a `/services/wex/state-machine` folder off root and move this into there. We can then follow a format of keeping service specific information in there.

**Comment by autotelik** [comment]
@Cruikshanks moved to suggested location

**Pull request merged**
