### PR TITLE
Add pull request guide to process

### PR DESCRIPTION
**Pull request by Cruikshanks**
This adds a detailed guide on how to go about creating, working with, and completing a pull request on any of the projects or respositories we maintain.

The intention is that the guide is detailed enough to answer all questions, make the process clear to all, without being so verbose no one actually reads it.

### CODE REVIEW

**Comment by Cruikshanks** [comment]
Could everyone take a look at the PR process I've outlined as soon as possible? I'm hoping to get everyones thoughts and the process bottomed out before we start work on the next service.

**Comment by reggieb** [comment]
I like: the emphasis on `rebase` over `merge`. Also the importance of the developer taking responsibility for keeping their code in line with the master/develop branches.

My first concern is the duplication of roles between the repository (git) and the project management system (Jira). I believe the nature of the work to be done and the reasons for doing it should be defined in Jira. Git should just record what has been done. With the proposed system, you're asking for the Jira ticket to be replicated in the first git commit message. I think the Jira ticket should be referenced in the git history - but a link to the ticket and use of the job number should be enough.

My second concern is over-complication. The fact that such a long document is needed to define the process, suggests that that process is not simple. Adding requirements such as squashing all commits adds extra complication and an additional mechanism whereby mistakes can be made (fixing a mistake made while squashing can be a pain).

**Comment by Cruikshanks** [comment]
Thank you so much for the thoughtful and detailed comments @reggieb . I have taken them onboard and have submitted a series of changes which I hope improve things. Coming back to your specific concerns

1. I believe that is a fault of the guide as written at the time. I **don't** want the Jira story to simply be rehashed in the PR/commit
  - This was essentially what was happening before, but when you actually looked at the changes made they did not appear relevant to the story. I want to commit message to reflect the actual change made.
  -  Our Jira stories tend to be *add page foo to journey* which I believe is too large for PR purposes. Using a basic example I believe breaking the work down into separate PR's e.g. add the model, add the controller, add the view (its late, I'm trying :weary:!) is more manageable.
2. I've endeavoured to simplify the process
  - For example coming up with a response to point 1 made me realise that a **QA** step wasn't practical, and that it conflicted with my goal of specific, focused commits. If the feature as set out in Jira increases in scope, or issues are found with what has been previously delivered, they *should* be tackled as separate changes rather than trying to keep them all within the original PR.
  - I tend to be a bit 'wordy' (check out this comment!) so I've gone back and and cleaned up some of the content, and deleted stuff that was trying to help but probably was just getting in the way.
  - I'm sticking to my guns on *squashing* though. I don't see it as a complicated process, and I believe gives a far cleaner and easier to read commit history.
  - I also believe its makes our lives as developers easier. Creating meaningful commit messages, and ensuring the message relates to the change can conflict with *commit often!* Squashing actually says its ok to throw the odd `WIP` in there, and not to worry about `Deleting foo because it was a stupid idea` as you know they'll all be cleaned up at the end.

**Comment by Cruikshanks** [comment]
Any comments from @woodpigeon or @autotelik :thought_balloon:?

**Comment by autotelik** [comment]
-Use the imperative mood 

do what ?

**Comment by Cruikshanks** [comment]
@autotelik The example given in the guide is your commit title would start with *Add ability* not *Added ability*. I believe its a standard convention for git commit messages and the [blog post](http://chris.beams.io/posts/git-commit/#seven-rules) pointed to in the article makes a clear case for it.

For example it points out git itself uses this form when making commit messages on your behalf.

- `git merge` leads to *Merge branch* not *Merged branch*
- `git revoke` leads to *Revert "add the thing"* not *Reverted "add the thing"*

The quick test Chris suggests you use when coming up with the commit title is

> A properly formed git commit subject line should always be able to complete the following sentence:
> - If applied, this commit will _**your subject line here**_
> 
> For example:
>
> - If applied, this commit will _**refactor subsystem X for readability**_
> - If applied, this commit will _**update getting started documentation**_
> - If applied, this commit will _**remove deprecated methods**_
> - If applied, this commit will _**release version 1.0.0**_
> - If applied, this commit will _**merge pull request #123 from user/branch**_
>
> Notice how this doesn't work for the other non-imperative forms:
> 
> - If applied, this commit will _**fixed bug with Y**_
> - If applied, this commit will _**changing behavior of X**_
> - If applied, this commit will _**more fixes for broken stuff**_
> - If applied, this commit will _**sweet new API methods**_

Does that help?

**Comment by Cruikshanks** [comment]
Calling this one to a close today. If I hear no more by the end of today I'll 🚢 it and this process will kick in for any new PR's and PR's in flight which are still under development.

**Pull request merged**
